# Generated by Django 4.2.13 on 2024-07-16 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='catalog.product', verbose_name='продукт'),
        ),
        migrations.AlterField(
            model_name='version',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Название версии'),
        ),
    ]
