# Generated by Django 4.2.13 on 2024-07-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("catalog", "0005_alter_product_category")]

    operations = [
        migrations.AlterField(
            model_name="contacts",
            name="address",
            field=models.TextField(help_text="Введите адрес", verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Укажите цену товара",
                max_digits=6,
                verbose_name="Цена",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.TextField(
                help_text="Введите наименование товара", verbose_name="Наименование"
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="number",
            field=models.CharField(
                help_text="Укажите номер версии",
                max_length=20,
                verbose_name="Номер версии",
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="title",
            field=models.TextField(
                blank=True,
                help_text="Введите название версии",
                null=True,
                verbose_name="Название версии",
            ),
        ),
    ]
